---
apiVersion: v1
data:
  values.yaml: |
    image:
      registry: ghcr.io
      repository: traefik/traefik-hub
      tag: "v3.17.11"
    hub:
      token: "XXXX"
      apiManagement:
        enabled: true
    aigateway:
      enabled: true
    ingressClass:
      isDefaultClass: false
      name: traefik-hub
    providers:
      kubernetesCRD:
        ingressClass: traefik-hub
      kubernetesIngress:
        ingressClass: traefik-hub
    additionalArguments:
      - "--entrypoints.web.http.redirections.entryPoint.to=:443"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
kind: ConfigMap
metadata:
  name: ${releaseName}-3.17.11-config-defaults
  namespace: ${releaseNamespace}
