apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${releaseName}-helmrelease
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  path: ./helmrelease
  postBuild:
    substitute:
      releaseName: ${releaseName}
      releaseNamespace: ${releaseNamespace}
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: OCIRepository
    name: ${releaseName}-source
    namespace: ${releaseNamespace}
  timeout: 1m0s
  wait: true
---
