name: Publish OCI Artifacts

on:
  workflow_call:
    inputs:
      COLLECTION_TAG:
        description: 'Tag to give to new version to be published'
        required: true
        type: string
      CONSTRAINT:
        description: "Constraints to filter the applications that are selected (e.g., nkpVersion=2.16)"
        required: false
        type: string
      APPS:
        description: "Apps to bundle (name=version)"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      COLLECTION_TAG:
        description: 'Tag to give to new version to be published'
        required: true
        type: string
      CONSTRAINT:
        description: "Constraints to filter the applications that are selected (e.g., nkpVersion=2.16)"
        required: false
        type: string
      APPS:
        description: "Apps to bundle (name=version)"
        required: false
        type: string

jobs:
  publish-oci-artifacts:
    name: Publish OCI Artifacts
    runs-on:
      - self-hosted-ncn-docker-medium
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token-ncn
        with:
          app-id: ${{ secrets.GHA_CHECKOUT_APP_ID }}
          private-key: ${{ secrets.GHA_CHECKOUT_APP_PRIVATE_KEY }}
          owner: nutanix-cloud-native

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true
          skip-nix-installation: true
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.app-token-ncn.outputs.token }}

      - name: Create and publish artifacts
        run: devbox run -- "GOOS=linux GOARCH=amd64 just create-publish-artifacts"
        env:
          COLLECTION_TAG: ${{ inputs.COLLECTION_TAG }}
          CONSTRAINT: ${{ inputs.CONSTRAINT }}
          APPS: ${{ inputs.APPS }}
