name: Black Duck Daily Policy Check
on:
  workflow_dispatch: # Enables manual triggering of the workflow
jobs:
  security:
    if: github.repository == 'nutanix-cloud-native/nkp-partner-catalog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Black Duck Full Scan
        uses: synopsys-sig/synopsys-action@v1.10.0
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackduck_scan_full: true
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
